Proposal for introducing UnwrapRight and UnwrapLeft for Either
FrancoMelandri/tiny-fp pull request #10
Opened 2022-02-17 16:47 UTC by fabiolune

Similar to `Unwrap` for `Option`, `UnwrapRight` and `UnwrapLeft` give access to the internal values if the monads is in the correct status, otherwise thy throw an `InvalidOperationException`

2022-02-17 17:31 UTC, FrancoMelandri requested changes

2022-02-17 21:04 UTC, fabio-lonegro-deltatre commented on tiny-fp.sln.DotSettings.user
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
Wtf... Sure I will

2022-02-17 21:47 UTC, fabiolune commented on tiny-fp.sln.DotSettings.user
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
done my friend 👍

2022-02-19 05:19 UTC, FrancoMelandri commented on src/DataTypes/Either/Either.cs
> +        public R UnwrapRight()
I don't want to bore you, but what do you think about something like map,bind,unwrap and maleft,bindleft,unwrapleft just for summery 😁

2022-02-19 05:21 UTC, closed without merging